import { Package, TravelCompany, Booking, Customer, Review } from '@/types';

// Travel Companies
export const travelCompanies: TravelCompany[] = [
  {
    id: 'travel-1',
    name: 'Al-Amin Travel',
    slug: 'al-amin-travel',
    logo: 'https://images.pexels.com/photos/1629785/pexels-photo-1629785.jpeg?auto=compress&cs=tinysrgb&w=100',
    coverImage: 'https://images.pexels.com/photos/2409097/pexels-photo-2409097.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Travel umrah terpercaya dengan pengalaman lebih dari 15 tahun. Menyelenggarakan perjalanan ibah dengan standar internasional.',
    address: 'Jl. Kebon Sirih No. 45',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    phone: '021-5555-123',
    email: 'info@alamintravel.id',
    website: 'https://alamintravel.id',
    isVerified: true,
    verificationDate: '2023-01-15',
    rating: 4.9,
    totalReviews: 1250,
    totalPackages: 48,
    totalCustomers: 8500,
    establishedYear: 2008,
    socialMedia: {
      instagram: '@alamintravel',
      facebook: 'alamintravel',
      youtube: 'alamintravelofficial'
    }
  },
  {
    id: 'travel-2',
    name: 'Mabrur Wisata',
    slug: 'mabrur-wisata',
    logo: 'https://images.pexels.com/photos/1898554/pexels-photo-1898554.jpeg?auto=compress&cs=tinysrgb&w=100',
    coverImage: 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Spesialis tour domestik dan internasional dengan fokus pada wisata halal. Melayani dengan pelayanan prima.',
    address: 'Jl. Sudirman No. 123',
    city: 'Bandung',
    province: 'Jawa Barat',
    phone: '022-7777-456',
    email: 'contact@mabrurwisata.id',
    website: 'https://mabrurwisata.id',
    isVerified: true,
    verificationDate: '2023-03-20',
    rating: 4.8,
    totalReviews: 890,
    totalPackages: 65,
    totalCustomers: 6200,
    establishedYear: 2010,
  },
  {
    id: 'travel-3',
    name: 'Safar Journey',
    slug: 'safar-journey',
    logo: 'https://images.pexels.com/photos/2372725/pexels-photo-2372725.jpeg?auto=compress&cs=tinysrgb&w=100',
    coverImage: 'https://images.pexels.com/photos/3278215/pexels-photo-3278215.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Menghadirkan pengalaman umrah dan haji khusus dengan fasilitas hotel bintang 5 dan maskapai premium.',
    address: 'Jl. Imam Bonjol No. 78',
    city: 'Surabaya',
    province: 'Jawa Timur',
    phone: '031-8888-999',
    email: 'info@safarjourney.id',
    website: 'https://safarjourney.id',
    isVerified: true,
    verificationDate: '2023-02-10',
    rating: 4.7,
    totalReviews: 650,
    totalPackages: 32,
    totalCustomers: 4100,
    establishedYear: 2012,
  },
];

// Packages
export const packages: Package[] = [
  {
    id: 'pkg-1',
    slug: 'umrah-reguler-9-hari',
    name: 'Paket Umrah Reguler 9 Hari',
    description: 'Paket umrah reguler dengan durasi 9 hari, menginap di hotel bintang 4 dekat Masjidil Haram. Dengan pembimbing berpengalaman dan fasilitas lengkap.',
    shortDescription: 'Umrah 9 hari dengan hotel bintang 4 dekat Masjidil Haram',
    type: 'open',
    category: 'umrah',
    destination: 'Makkah & Madinah',
    departureCity: 'Jakarta',
    duration: 9,
    price: 28500000,
    originalPrice: 32000000,
    departureDate: '2024-03-15',
    returnDate: '2024-03-23',
    airline: 'Saudi Arabian Airlines',
    airlineImage: 'https://flagcdn.com/w40/sa.png',
    hotelRating: 4,
    hotelName: 'Pullman ZamZam Hotel',
    seatsTotal: 45,
    seatsAvailable: 12,
    images: [
      'https://images.pexels.com/photos/2409097/pexels-photo-2409097.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/5703631/pexels-photo-5703631.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1629785/pexels-photo-1629785.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    facilities: ['Hotel Bintang 4', 'Pesawat Wide Body', 'Makan 3x Sehari', 'Bus AC', 'ZamZam Gratis', 'Perlengkapan Ihram', 'Pembimbing Profesional', 'Visa Umrah'],
    included: [
      'Tiket pesawat PP',
      'Hotel bintang 4 (twin share)',
      'Makan 3x sehari',
      'Transportasi bus AC',
      'ZamZam 5 liter',
      'Perlengkapan ihram',
      'Bimbingan manasik',
      'Perlengkapan wisata',
      'Visa umrah',
      'Asuransi perjalanan',
      'Tour leader berpengalaman',
    ],
    excluded: [
      'Biaya paspor',
      'Biaya tambahan single room',
      'Tip wajib (optional)',
      'Pengeluaran pribadi',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Keberangkatan',
        description: 'Berkumpul di Bandara Soekarno-Hatta, penerbangan ke Jeddah',
        activities: ['Check-in bandara', 'Penerbangan ke Jeddah', 'Tiba dan istirahat'],
        meals: ['Makan malam di pesawat']
      },
      {
        day: 2,
        title: 'Tiba di Makkah',
        description: 'Tiba di Jeddah, perjalanan ke Makkah dan melakukan Umrah Pertama',
        activities: ['Proses imigrasi', 'Perjalanan ke Makkah', 'Check-in hotel', 'Umrah pertama'],
        meals: ['Sarapan', 'Makan siang', 'Makan malam']
      },
      {
        day: 3,
        title: 'Ibadah di Makkah',
        description: 'Fokus ibadah di Masjidil Haram',
        activities: ['Sholat subuh di Masjidil Haram', 'Tawaf dan Sai', 'Kuliah singkat', 'Ibadah bebas'],
        meals: ['Sarapan', 'Makan siang', 'Makan malam']
      },
      {
        day: 4,
        title: 'Pindah ke Madinah',
        description: 'Perjalanan ke Madinah dan ibadah pertama di Masjid Nabawi',
        activities: ['Check-out hotel', 'Perjalanan ke Madinah', 'Check-in hotel', 'Sholat di Raudhah'],
        meals: ['Sarapan', 'Makan siang', 'Makan malam']
      },
      {
        day: 5,
        title: 'Ibadah di Madinah',
        description: 'Fokus ibadah di Masjid Nabawi',
        activities: ['Sholat di Masjid Nabawi', 'Ziarah Makam Rasulullah', 'Ziarah Baqi', 'Kuliah singkat'],
        meals: ['Sarapan', 'Makan siang', 'Makan malam']
      },
      {
        day: 6,
        title: 'Ziarah Madinah',
        description: 'Ziarah ke tempat bersejarah di sekitar Madinah',
        activities: ['Ziarah Uhud', 'Ziarah Masjid Qiblatain', 'Ziarah Masjid Quba', 'Ibadah bebas'],
        meals: ['Sarapan', 'Makan siang', 'Makan malam']
      },
      {
        day: 7,
        title: 'Kembali ke Makkah',
        description: 'Perjalanan kembali ke Makkah',
        activities: ['Check-out hotel', 'Perjalanan ke Makkah', 'Check-in hotel', 'Umrah sunnah'],
        meals: ['Sarapan', 'Makan siang', 'Makan malam']
      },
      {
        day: 8,
        title: 'Hari Terakhir di Makkah',
        description: 'Ibadah terakhir dan persiapan kepulangan',
        activities: ['Sholat subuh terakhir', 'Tawaf wada', 'Belanja cenderamata', 'Check-out hotel'],
        meals: ['Sarapan', 'Makan siang', 'Makan malam']
      },
      {
        day: 9,
        title: 'Kepulangan',
        description: 'Perjalanan pulang ke Indonesia',
        activities: ['Perjalanan ke Jeddah', 'Proses imigrasi', 'Penerbangan ke Jakarta', 'Tiba di Jakarta'],
        meals: ['Sarapan', 'Makan di pesawat']
      },
    ],
    termsConditions: [
      'DP minimal 30% untuk reservasi',
      'Pelunasan maksimal 14 hari sebelum keberangkatan',
      'Pembatalan 30 hari sebelum keberangkatan: pengembalian 75%',
      'Pembatalan 14 hari sebelum keberangkatan: pengembalian 50%',
      'Pembatalan kurang dari 7 hari: tidak ada pengembalian',
      'Syarat paspor minimal 6 bulan berlaku',
      'Kartu kuning vaksin meningitis wajib',
    ],
    faqs: [
      {
        question: 'Apakah ada bimbingan manasik?',
        answer: 'Ya, kami menyediakan bimbingan manasik 2x sebelum keberangkatan di kantor kami atau secara online.'
      },
      {
        question: 'Berapa minimal usia peserta?',
        answer: 'Usia minimal 5 tahun dengan pendamping orang tua.'
      },
      {
        question: 'Apakah bisa single traveller?',
        answer: 'Bisa dengan tambahan biaya single supplement sebesar Rp 5.000.000.'
      },
      {
        question: 'Bagaimana jika paket dibatalkan?',
        answer: 'Jika pembatalan dari pihak travel, uang dikembalikan 100% atau dipindahkan ke jadwal berikutnya.'
      },
    ],
    travelId: 'travel-1',
    travel: travelCompanies[0],
    reviews: [],
    averageRating: 4.9,
    totalReviews: 85,
    isVisaIncluded: true,
    isMealsIncluded: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-20',
  },
  {
    id: 'pkg-2',
    slug: 'umrah-plus-turki-12-hari',
    name: 'Paket Umrah Plus Turki 12 Hari',
    description: 'Paket umrah plus turki dengan kombinasi wisata islami di Istanbul. Nikmati keindahan arsitektur Ottoman dan sejarah Islam.',
    shortDescription: 'Umrah + wisata Turki dengan hotel bintang 5',
    type: 'open',
    category: 'umrah',
    destination: 'Makkah, Madinah & Istanbul',
    departureCity: 'Jakarta',
    duration: 12,
    price: 45000000,
    departureDate: '2024-04-10',
    returnDate: '2024-04-21',
    airline: 'Turkish Airlines',
    airlineImage: 'https://flagcdn.com/w40/tr.png',
    hotelRating: 5,
    hotelName: 'Swissotel Makkah',
    seatsTotal: 30,
    seatsAvailable: 8,
    images: [
      'https://images.pexels.com/photos/3278215/pexels-photo-3278215.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2409097/pexels-photo-2409097.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/5703631/pexels-photo-5703631.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    facilities: ['Hotel Bintang 5', 'Turkish Airlines', 'Makan 3x Sehari', 'Bus Premium', 'ZamZam Gratis', 'Tour Istanbul'],
    included: [
      'Tiket pesawat PP via Istanbul',
      'Hotel bintang 5',
      'Tour Istanbul 3 hari',
      'Semua tiket masuk wisata',
      'Makan 3x sehari',
      'Transportasi bus premium',
      'ZamZam 5 liter',
      'Visa umrah & Turki',
      'Asuransi perjalanan',
    ],
    excluded: ['Biaya paspor', 'Tip optional', 'Pengeluaran pribadi'],
    itinerary: [
      { day: 1, title: 'Keberangkatan', description: 'Penerbangan Jakarta-Istanbul', activities: [], meals: [] },
      { day: 2, title: 'Tiba Istanbul', description: 'Tiba di Istanbul, city tour', activities: [], meals: [] },
      { day: 3, title: 'Tour Istanbul', description: 'Wisata Istanbul: Blue Mosque, Hagia Sophia', activities: [], meals: [] },
      { day: 4, title: 'Turki to Jeddah', description: 'Penerbatan Istanbul-Jeddah', activities: [], meals: [] },
      { day: 5, title: 'Makkah', description: 'Tiba di Makkah, Umrah pertama', activities: [], meals: [] },
      { day: 6, title: 'Ibadah Makkah', description: 'Ibadah di Masjidil Haram', activities: [], meals: [] },
      { day: 7, title: 'Madinah', description: 'Perjalanan ke Madinah', activities: [], meals: [] },
      { day: 8, title: 'Ibadah Madinah', description: 'Ibadah di Masjid Nabawi', activities: [], meals: [] },
      { day: 9, title: 'Ziarah Madinah', description: 'Ziarah Uhud & Quba', activities: [], meals: [] },
      { day: 10, title: 'Kembali Makkah', description: 'Kembali ke Makkah', activities: [], meals: [] },
      { day: 11, title: 'Tawaf Wada', description: 'Ibadah terakhir & persiapan pulang', activities: [], meals: [] },
      { day: 12, title: 'Kepulangan', description: 'Penerbangan Jeddah-Jakarta', activities: [], meals: [] },
    ],
    termsConditions: ['DP minimal 30%', 'Pelunasan H-14', 'Visa Turki ditanggung travel'],
    faqs: [],
    travelId: 'travel-2',
    travel: travelCompanies[1],
    reviews: [],
    averageRating: 4.8,
    totalReviews: 42,
    isVisaIncluded: true,
    isMealsIncluded: true,
    createdAt: '2024-02-01',
    updatedAt: '2024-02-05',
  },
  {
    id: 'pkg-3',
    slug: 'tour-domestik-bromo-3-hari',
    name: 'Tour Bromo Tengger Semeru 3 Hari 2 Malam',
    description: 'Petualangan mengagumkan ke keindahan Gunung Bromo dan Gunung Semeru. Nikmati matahari terbit spektakuler dengan latar belakang kaldera vulkanik.',
    shortDescription: 'Wisata Bromo dengan penginapan nyaman',
    type: 'open',
    category: 'tour-domestik',
    destination: 'Gunung Bromo, Jawa Timur',
    departureCity: 'Surabaya',
    duration: 3,
    price: 2500000,
    originalPrice: 3200000,
    departureDate: '2024-03-20',
    returnDate: '2024-03-22',
    airline: 'Bus Wisata',
    hotelRating: 3,
    hotelName: 'Cemara Indah Hotel',
    seatsTotal: 20,
    seatsAvailable: 6,
    images: [
      'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1898554/pexels-photo-1898554.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    facilities: ['Hotel Bintang 3', 'Jeep 4WD', 'Makan 3x Sehari', 'Pemandu Lokal', 'Tiket Masuk'],
    included: ['Transportasi dari Surabaya', 'Hotel 2 malam', 'Jeep Bromo', 'Semua tiket masuk', 'Makan selama tour'],
    excluded: ['Pengeluaran pribadi', 'Tip pemandu'],
    itinerary: [
      { day: 1, title: 'Keberangkatan', description: 'Penjemputan di Surabaya, perjalanan ke Bromo', activities: [], meals: [] },
      { day: 2, title: 'Sunrise Bromo', description: 'Bukit Kingkong untuk sunrise, Penanjakan, Bromo', activities: [], meals: [] },
      { day: 3, title: 'Wisata Sekitar', description: 'Pasir Berbisik, Savanna, kepulangan', activities: [], meals: [] },
    ],
    termsConditions: ['DP 50%', 'Pelunasan H-7'],
    faqs: [],
    travelId: 'travel-3',
    travel: travelCompanies[2],
    reviews: [],
    averageRating: 4.7,
    totalReviews: 156,
    isVisaIncluded: false,
    isMealsIncluded: true,
    createdAt: '2024-02-10',
    updatedAt: '2024-02-12',
  },
  {
    id: 'pkg-4',
    slug: 'umrah-premium-bintang-5',
    name: 'Paket Umrah Premium Bintang 5',
    description: 'Paket umrah premium dengan hotel bintang 5 dekat Masjidil Haram. Fasilitas mewah dengan pelayanan VIP.',
    shortDescription: 'Umrah premium dengan hotel bintang 5',
    type: 'open',
    category: 'umrah',
    destination: 'Makkah & Madinah',
    departureCity: 'Jakarta',
    duration: 10,
    price: 38500000,
    departureDate: '2024-05-01',
    returnDate: '2024-05-10',
    airline: 'Garuda Indonesia',
    airlineImage: 'https://flagcdn.com/w40/id.png',
    hotelRating: 5,
    hotelName: 'Fairmont Makkah Clock Tower',
    seatsTotal: 25,
    seatsAvailable: 15,
    images: [
      'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2409097/pexels-photo-2409097.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    facilities: ['Hotel Bintang 5', 'Garuda Indonesia Business', 'Makan Premium', 'VIP Lounge', 'ZamZam Premium'],
    included: ['Tiket Garida Indonesia bisnis class', 'Hotel Fairmont', 'Makan premium', 'VIP handling', 'Visa umrah'],
    excluded: ['Tip', 'Pengeluaran pribadi'],
    itinerary: [],
    termsConditions: ['DP 40%', 'Pelunasan H-21'],
    faqs: [],
    travelId: 'travel-1',
    travel: travelCompanies[0],
    reviews: [],
    averageRating: 4.95,
    totalReviews: 67,
    isVisaIncluded: true,
    isMealsIncluded: true,
    createdAt: '2024-02-20',
    updatedAt: '2024-02-22',
  },
  {
    id: 'pkg-5',
    slug: 'haji-plus-fonabih',
    name: 'Paket Haji Plus FONABIH 40 Hari',
    description: 'Paket haji plus dengan durasi 40 hari, akomodasi hotel berbintang dan fasilitas lengkap.',
    shortDescription: 'Haji plus dengan fasilitas lengkap',
    type: 'open',
    category: 'haji-khusus',
    destination: 'Makkah & Madinah',
    departureCity: 'Jakarta',
    duration: 40,
    price: 185000000,
    departureDate: '2024-06-01',
    returnDate: '2024-07-10',
    airline: 'Saudi Arabian Airlines',
    airlineImage: 'https://flagcdn.com/w40/sa.png',
    hotelRating: 5,
    hotelName: 'InterContinental Dar Al Tawhid',
    seatsTotal: 15,
    seatsAvailable: 5,
    images: [
      'https://images.pexels.com/photos/5703631/pexels-photo-5703631.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    facilities: ['Hotel Bintang 5', 'Transportasi VIP', 'Makan Halal Premium', 'Tim Medis', 'Pembimbing Khusus'],
    included: [
      'Tiket pesawat PP',
      'Hotel Makkah & Madinah bintang 5',
      'Makan sepanjang perjalanan',
      'Transportasi VIP',
      'Tim medis pendamping',
      'Visa haji',
      'Kurban',
    ],
    excluded: ['Pengeluaran pribadi', 'Tip wajib'],
    itinerary: [],
    termsConditions: ['DP 50%', 'Pelunasan H-30', 'Syarat usia minimal'],
    faqs: [],
    travelId: 'travel-1',
    travel: travelCompanies[0],
    reviews: [],
    averageRating: 4.9,
    totalReviews: 23,
    isVisaIncluded: true,
    isMealsIncluded: true,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-05',
  },
  {
    id: 'pkg-6',
    slug: 'wisata-halal-jepang',
    name: 'Wisata Halal Jepang 8 Hari',
    description: 'Temukan keindahan Jepang dengan tur halal lengkap. Makanan halal, restoran halal, dan keindahan bunga sakura.',
    shortDescription: 'Tour Jepang dengan menu halal',
    type: 'open',
    category: 'wisata-halal',
    destination: 'Tokyo, Kyoto, Osaka',
    departureCity: 'Jakarta',
    duration: 8,
    price: 28000000,
    departureDate: '2024-04-15',
    returnDate: '2024-04-22',
    airline: 'All Nippon Airways',
    airlineImage: 'https://flagcdn.com/w40/jp.png',
    hotelRating: 4,
    hotelName: 'Shinjuku Granbell Hotel',
    seatsTotal: 25,
    seatsAvailable: 10,
    images: [
      'https://images.pexels.com/photos/2506910/pexels-photo-2506910.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2187605/pexels-photo-2187605.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    facilities: ['Hotel Bintang 4', 'Makan Halal', 'Transportasi JR Pass', 'Pemandu Berpengalaman'],
    included: ['Tiket pesawat', 'Hotel bintang 4', 'JR Pass', 'Makan halal', 'Tiket wisata', 'Pemandu'],
    excluded: ['Bea masuk', 'Pengeluaran pribadi'],
    itinerary: [],
    termsConditions: ['DP 40%', 'Pelunasan H-14'],
    faqs: [],
    travelId: 'travel-2',
    travel: travelCompanies[1],
    reviews: [],
    averageRating: 4.85,
    totalReviews: 89,
    isVisaIncluded: true,
    isMealsIncluded: true,
    createdAt: '2024-02-28',
    updatedAt: '2024-03-02',
  },
];

// Reviews
export const reviews: Review[] = [
  {
    id: 'rev-1',
    rating: 5,
    comment: 'Pelayanan sangat memuaskan! Hotel dekat dengan Masjidil Haram, tour leader sangat sabar membimbing jamaah. Terima kasih SafarHub!',
    customerId: 'cust-1',
    customerName: 'Ahmad Fauzi',
    customerAvatar: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=100',
    packageId: 'pkg-1',
    travelId: 'travel-1',
    createdAt: '2024-02-15',
  },
  {
    id: 'rev-2',
    rating: 5,
    comment: 'Pengalaman umrah pertama saya sangat berkesan. Semua fasilitas sesuai dengan yang diiklankan. Highly recommended!',
    customerId: 'cust-2',
    customerName: 'Siti Nurhaliza',
    customerAvatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100',
    packageId: 'pkg-1',
    travelId: 'travel-1',
    createdAt: '2024-02-10',
    reply: {
      content: 'Terima kasih atas kepercayaan, Bu Siti. Semoga ibadah umrahnya mabrur!',
      repliedAt: '2024-02-12'
    }
  },
  {
    id: 'rev-3',
    rating: 4,
    comment: 'Fasilitas lengkap, makanan enak. Hanya saja perjalanan darat cukup panjang, mungkin bisa diatur lebih baik.',
    customerId: 'cust-3',
    customerName: 'Budi Santoso',
    packageId: 'pkg-1',
    travelId: 'travel-1',
    createdAt: '2024-01-28',
  },
];

// Sample Bookings
export const bookings: Booking[] = [
  {
    id: 'booking-1',
    code: 'SH-2024-000001',
    packageId: 'pkg-1',
    packageName: 'Paket Umrah Reguler 9 Hari',
    customerId: 'cust-1',
    customer: {
      id: 'cust-1',
      name: 'Ahmad Fauzi',
      email: 'ahmad.fauzi@email.com',
      phone: '081234567890',
      address: 'Jl. Sudirman No. 123',
      city: 'Jakarta',
      province: 'DKI Jakarta',
      postalCode: '12345',
      nik: '3171234567890001',
      passportNumber: 'A1234567',
      passportExpiry: '2025-12-31',
    },
    passengers: [
      {
        id: 'pass-1',
        name: 'Ahmad Fauzi',
        relationship: 'Diri Sendiri',
        nik: '3171234567890001',
        passportNumber: 'A1234567',
        birthDate: '1985-05-15',
        gender: 'male',
      },
      {
        id: 'pass-2',
        name: 'Siti Aisyah',
        relationship: 'Istri',
        nik: '3171234567890002',
        passportNumber: 'A1234568',
        birthDate: '1988-08-20',
        gender: 'female',
      },
    ],
    status: 'confirmed',
    paymentStatus: 'paid',
    totalAmount: 57000000,
    paidAmount: 57000000,
    departureDate: '2024-03-15',
    createdAt: '2024-01-20',
    updatedAt: '2024-02-01',
    timeline: [
      { status: 'Booking Created', description: 'Booking berhasil dibuat', timestamp: '2024-01-20 10:00:00', isCompleted: true },
      { status: 'Payment Confirmed', description: 'Pembayaran dikonfirmasi', timestamp: '2024-01-21 14:30:00', isCompleted: true },
      { status: 'Documents Uploaded', description: 'Dokumen lengkap', timestamp: '2024-01-25 09:00:00', isCompleted: true },
      { status: 'Booking Confirmed', description: 'Booking dikonfirmasi oleh travel', timestamp: '2024-01-26 16:00:00', isCompleted: true },
    ],
  },
];

// Format currency
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

// Format date
export function formatDate(date: string, format: 'short' | 'long' = 'short'): string {
  const d = new Date(date);
  if (format === 'short') {
    return d.toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' });
  }
  return d.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
}

// Format date range
export function formatDateRange(start: string, end: string): string {
  const startDate = new Date(start);
  const endDate = new Date(end);
  const startFormatted = startDate.toLocaleDateString('id-ID', { day: 'numeric', month: 'short' });
  const endFormatted = endDate.toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' });
  return `${startFormatted} - ${endFormatted}`;
}

// Calculate discount percentage
export function calculateDiscount(original: number, current: number): number {
  return Math.round(((original - current) / original) * 100);
}
